### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by ssbrshei** [ylipacbio/libcppII#1]
Hi,

I tried to compile this package on a Red Hat Enterprise Linux 6.6 system with GCC 4.4.7 and ran into problem. Here is an excerpt of the error:

--------------------
g++ -O3 -std=c++0x -pedantic -c -fmessage-length=0 -MMD -MP -I../../../../../assembly/seymour/dist/common/include -I/l/hdf5-1.8.14/include -I../pbdata -MF"BufferedHDF2DArray.d" -MT"BufferedHDF2DArray.o BufferedHDF2DArray.d" -o BufferedHDF2DArray.o BufferedHDF2DArray.cpp
In file included from HDFGroup.hpp:9,
                 from HDFData.hpp:7,
                 from BufferedHDF2DArray.hpp:9,
                 from BufferedHDF2DArray.cpp:1:
HDFAttributable.hpp:8: error: variable or field 'CallStoreAttributeName' declared void
HDFAttributable.hpp:8: error: 'H5Location' is not a member of 'H5'
HDFAttributable.hpp:8: error: 'obj' was not declared in this scope
HDFAttributable.hpp:8: error: expected primary-expression before 'attrName'
HDFAttributable.hpp:8: error: expected primary-expression before 'void'
HDFAttributable.hpp:14: error: 'H5::H5Location' has not been declared
HDFAttributable.hpp:17: error: ISO C++ forbids declaration of 'H5Location' with no type
HDFAttributable.hpp:17: error: invalid use of '::'
HDFAttributable.hpp:17: error: expected ';' before '*' token
In file included from HDFData.hpp:7,
                 from BufferedHDF2DArray.hpp:9,
                 from BufferedHDF2DArray.cpp:1:
HDFGroup.hpp:24: error: ISO C++ forbids declaration of 'H5Location' with no type
HDFGroup.hpp:24: error: invalid use of '::'
HDFGroup.hpp:24: error: expected ';' before '*' token
In file included from BufferedHDF2DArray.hpp:9,
                 from BufferedHDF2DArray.cpp:1:
HDFData.hpp:21: error: ISO C++ forbids declaration of 'H5Location' with no type
HDFData.hpp:21: error: invalid use of '::'
HDFData.hpp:21: error: expected ';' before '*' token
make[1]: *** [BufferedHDF2DArray.o] Error 1
make[1]: Leaving directory `/nfs/nfs5-insecure/home/insecure-ro/software/rhel6_x86_64/python2.7.5/local/Consensus/blasr_libcpp/hdf'
make: *** [all] Error 2
------------------------------------

Any suggestion?

Thanks!

**Comment by ylipacbio** [comment]
Hi ssbrshei, 

H5Location is a class recently added to hdf5 1.8.12+ (for example 1.8.4 does not have it). This error log sounds like that you may have installed two versions hdf5 and libcpp is linking to an old version. Would you please edit blasr_git_common.mk, point HDF5_ROOT to hdf5-1.8.14 and re-make the build?

Thanks!
Yuan

**Comment by ssbrshei** [comment]
Hi Yuan,

Thank you so much for the reply. I will give it a try.

Shing-Shong

**Comment by ssbrshei** [comment]
Hi Yuan,

I take a look at the git files that I downloaded by

git clone https://github.com/PacificBiosciences/blasr_libcpp

But there is no file named blasr_git_common.mk. Doing a

   fgrep -rl HDF5_ROOT .

did not show any file that contains the string HDF5_ROOT.

I have the HDF5 1.8.14 installed (albeit to a different location as we
don't want that to interfere with the RPM version).

Thanks,
Shing-Shong

**Comment by ssbrshei** [comment]
Also I forgot to mention that I actually have already modified the
hdf/Makefile to include the location that I installed the hdf5 (in
/l/hdf5-1.8.14/).

INCLUDES = -I../../../../../assembly/seymour/dist/common/include \
                   *-I/l/hdf5-1.8.14/include \*
                   -I../pbdata

when I first reported the problem.

Thanks,
Shing-Shong

**Comment by ylipacbio** [comment]
Hi Shing-Shong,

That code base is quite old, you may git clone the following, which is more up to date. 

    git clone git@github.com:ylipacbio/refactored_blasr_II.git --recursive

blasr_git_common.mk is under the root directory and you may edit it to specify HDF5_ROOT.

**Comment by ssbrshei** [comment]
Thanks. But I got the following error:

# git clone git@github.com:ylipacbio/refactored_blasr_II.git --recursive
Initialized empty Git repository in
/l/python2.7.5/local/Consensus/refactored_blasr_II/.git/
Warning: Permanently added the RSA host key for IP address
'192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by ssbrshei** [comment]
git clone https://github.com/PacificBiosciences/refactored_blasr_II
--recursive

works.

**Comment by ylipacbio** [comment]
I am trying to make this repo public.

**Comment by ssbrshei** [comment]
You were right that the mix of two versions fo hdf5 was the problem. In
BufferedHDF2DArray.hpp, you have

#include "H5Cpp.h"

which does not exist in HDF5 1.8.14 anymore. As the result, it finds the
/usr/include/H5Cpp.h which is from an older HDF 1.8.5. Here is a list of
the header files installed by HDF 1.8.14:

H5ACpublic.h  H5Dpublic.h   H5FDdirect.h  H5FDmulti.h   H5Gpublic.h  
H5MMpublic.h  H5PTpublic.h  H5TBpublic.h  hdf5_hl.h
H5api_adpt.h  H5DSpublic.h  H5FDfamily.h  H5FDpublic.h  H5IMpublic.h 
H5Opublic.h   H5pubconf.h   H5Tpublic.h
H5Apublic.h   H5Epubgen.h   H5FDlog.h     H5FDsec2.h    H5Ipublic.h  
H5overflow.h  H5public.h    H5version.h
H5Cpublic.h   H5Epublic.h   H5FDmpi.h     H5FDstdio.h   H5Lpublic.h  
H5PLextern.h  H5Rpublic.h   H5Zpublic.h
H5DOpublic.h  H5FDcore.h    H5FDmpio.h    H5Fpublic.h   H5LTpublic.h 
H5Ppublic.h   H5Spublic.h   hdf5.h

Thanks.

**Comment by ylipacbio** [comment]
HDF5 1.8.14 does have these files, but you need to install HDF5 1.8.14 with cxx. e.g., 

    ./configure --prefix=path_to_your_hdf5_install_dir   --enable-cxx --with-szlib

You will find missing files such as H5Cpp.h under the installation directory.

**Comment by ssbrshei** [comment]
Great! Thanks for the information.

**Comment by ssbrshei** [comment]
Finally I was able to generate the blasr. I have to take out the -static though. Otherwise, for some unknown reason, I got the error:

H5PL.c:(.text+0x2b9): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lm

even thought the libm.a exists in /usr/lib64/. Thanks again for your help.
